### ISSUE TITLE
Proper style guide/contributing guidelines

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#269]

**Comment by 17cupsofcoffee** [comment]
A few thoughts on this:

* The section template you've made in https://raw.githubusercontent.com/rust-gamedev/rust-gamedev.github.io/source/newsletter-template.md is good! It could be a good idea to either add it to the README or your coordination issues each month so that people can't miss it.
* Similarly, could be good to list the full set of things that `markdownlint` enforces in the README/coordination issues - the big ones that trip people up being:
    * Line breaks at 80 characters
    * Dashes for lists instead of asterisks
    * No double linebreaks
    * No trailing punctuation or whitespace
* Maybe we should encourage people to install a `markdownlint` [extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) in their editor? That way they'll be guided towards a style that matches what we have on CI.
* We could add a PR template with a link to wherever we put these guidelines so that people see it before they submit (that'd be especially good for people who write their newsletter entries via the GitHub web editor, and so don't see the changes in an editor/previewed beforehand).
* We should also nudge people to check the result of the CI build - I feel like every month I have to go through and comment to get people to fix formatting issues and it'd save a lot of time if people checked beforehand!

None of this guarentees that people will actually read the guidelines, but it would be nice to have a easy link to point people to a go "this is what good looks like".

**Comment by ozkriff** [comment]
Sounds reasonable. I'm working on `CONTRIBUTING.md` with a compilation of all the style stuff and `.github/PULL_REQUEST_TEMPLATE.md` with a link to it.
