### ISSUE TITLE
Twitter preview

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/rust-gamedev.github.io#31]
Atm, the twitter preview is quite boring:

![image](https://user-images.githubusercontent.com/662976/67164808-116cfa80-f387-11e9-8070-d656c0dacaa6.png)

It may be worth to investigate additional meta tags a little to make it look nicer:
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary

**Comment by 17cupsofcoffee** [comment]
Looking at the site, there does appear to be some relevant meta tags in there already, courtesy of a plugin:

**Comment by 17cupsofcoffee** [comment]
#42 would indirectly fix this (by virtue of Rewriting The Whole Dang Thing), if we decide to go that route.

**Comment by 17cupsofcoffee** [comment]
With the updated tags from the Zola rewrite, the preview for a post now looks like this:

![image](https://user-images.githubusercontent.com/784533/69903074-f087c400-138c-11ea-801c-ae98b8f6d77c.png)

Main differences being that we have a higher-res image and more control over the text displayed. I've got it set up so that it'll display the [post summary](https://www.getzola.org/documentation/content/page/#summary) if one exists, or the first 100 words if not. Let me know if you're happy with this, or if you think it needs any more tweaks :)

**Comment by ozkriff** [comment]
Awesome!
