### ISSUE TITLE
Create a rust-gamedev.github.io site

### ISSUE THREAD

**Issue by AlexEne** [rust-gamedev/rust-gamedev.github.io#4]
We need a way to communicate status, news and other things.   

The first idea I have is a site like https://rustwasm.github.io/ or any of the other wgs

**Comment by ozkriff** [comment]
Maybe the background shouldn't be blue? It looks a little bit weird with red emojis without an outline of my system's font:

![image](https://user-images.githubusercontent.com/662976/63150270-0ad0a880-c00f-11e9-83b8-256bb7845faa.png)

**Comment by 17cupsofcoffee** [comment]
Hm, yeah, that's unfortunate - on Windows 10 they have nice black borders:

![image](https://user-images.githubusercontent.com/784533/63210397-ad5b5b00-c0e5-11e9-8a24-ee0f3e667718.png)

If we can't rely on them looking vaguely consistent across platforms, they should probably be removed/replaced. I only really put them there because I was jealous of the WASM WG's hard-hat Ferris :p

I'm not particularly attached to the blue either, picking out color schemes has never really been my strong suit. As long as whatever we choose passes the Chrome accessibility audit, I'm happy.

**Comment by zicklag** [comment]
> If we can't rely on them looking vaguely consistent across platforms, they should probably be removed/replaced. 

I think you should be able to make the display consistant if you provide a downloadable font and set that as the font-family. That way every system uses the same icons instead of each one using its system default.

Also, there might be a way to extract the SVG from a font and put SVG icons in there instead.

---

Also, I have experience with [Quasar](https://quasar.dev) for building websites if that seems like a direction you might want to take. See https://github.com/rust-gamedev/wg/issues/43#issue-481821892. If you guys are satisfied with Jekyll then go with that, but the option is out there if you need it.

**Comment by AlexEne** [comment]
If nobody has anything against this, I can go ahead and close this one and we can open more targeted issues if needed. (like one for font icons if we want to change/fix them them). Otherwise it gets to be too big of an issue.

**Comment by 17cupsofcoffee** [comment]
Don't think there's anything left to do here that's not covered by other issues, so I think this can be closed now.
